import { CreatePanel } from "@/components/create-panel";
import { DataTable } from "@/components/data-table";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { fetchData } from "@/lib/page-data";
import { LogoUpload } from "@/components/logo-upload";

interface Settings { tradeName: string; legalName: string; slug: string; timezone: string; settings?: { contactEmail?: string; contactPhone?: string; website?: string; primaryColor: string } }
interface Overview { legalAreas: Array<{ id: string; name: string; code: string; isActive: boolean }> }
export default async function SettingsPage() { const [data, overview] = await Promise.all([fetchData<Settings>("/v1/admin/settings"), fetchData<Overview>("/v1/admin/overview")]); return <><PageHeader eyebrow={data.slug} title="Configurações" description={`${data.legalName} · ${data.timezone}`} action={<div className="flex gap-2"><CreatePanel title="Dados do escritório" endpoint="/api/v1/admin/settings" method="PATCH" buttonLabel="Editar escritório" fields={[{ name: "tradeName", label: "Nome do escritório", required: true, defaultValue: data.tradeName }, { name: "contactEmail", label: "E-mail", type: "email", defaultValue: data.settings?.contactEmail }, { name: "contactPhone", label: "Telefone", defaultValue: data.settings?.contactPhone }, { name: "website", label: "Site", defaultValue: data.settings?.website }, { name: "primaryColor", label: "Cor principal", required: true, defaultValue: data.settings?.primaryColor ?? "#06B6D4" }]} /><CreatePanel title="Nova área jurídica" endpoint="/api/v1/admin/legal-areas" buttonLabel="Nova área" fields={[{ name: "name", label: "Nome", required: true }, { name: "description", label: "Descrição", type: "textarea" }]} /></div>} /><div className="mb-8 rounded-xl border bg-card p-5"><h2 className="mb-3 font-semibold">Logo do escritório</h2><LogoUpload /></div><h2 className="mb-3 text-lg font-semibold">Áreas jurídicas</h2><DataTable columns={["Código", "Área", "Situação"]} rows={overview.legalAreas.map((x) => [x.code, x.name, <StatusBadge key={x.id} value={x.isActive ? "ACTIVE" : "INACTIVE"} />])} /></>; }
