"use client";
import { LoaderCircle, Pencil, Plus, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

interface Template { id: string; name: string; legalAreaId: string; caseType?: string; isActive: boolean; items: Array<{ title: string }> }
export function ChecklistTemplateForm({ areas, template }: { areas: Array<{ id: string; name: string }>; template?: Template }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>(); const router = useRouter();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(undefined); const data = new FormData(event.currentTarget); const body = { name: String(data.get("name")), legalAreaId: String(data.get("legalAreaId")), caseType: String(data.get("caseType") ?? "") || undefined, isActive: data.get("isActive") === "on", items: String(data.get("items")).split(/\r?\n/).map((title) => title.trim()).filter(Boolean).map((title) => ({ title, isRequired: true })) }; const response = await fetch(template ? `/api/v1/checklists/templates/${template.id}` : "/api/v1/checklists/templates", { method: template ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); setSaving(false); if (!response.ok) { const problem = await response.json().catch(() => ({})) as { detail?: string; title?: string }; setError(problem.detail ?? problem.title ?? "Falha ao salvar modelo."); return; } setOpen(false); router.refresh(); }
  return <><Button variant={template ? "ghost" : "default"} onClick={() => setOpen(true)}>{template ? <Pencil className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}{template ? "Editar" : "Novo modelo"}</Button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={submit} className="grid w-full max-w-2xl gap-4 rounded-xl border bg-card p-6 sm:grid-cols-2"><div className="flex items-center justify-between sm:col-span-2"><h2 className="text-lg font-semibold">{template ? "Editar modelo" : "Novo modelo"}</h2><Button type="button" variant="ghost" size="icon" onClick={() => setOpen(false)}><X /></Button></div><div className="space-y-2"><Label>Nome</Label><Input name="name" required defaultValue={template?.name} /></div><div className="space-y-2"><Label>Área jurídica</Label><select name="legalAreaId" required defaultValue={template?.legalAreaId} className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Selecione</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select></div><div className="space-y-2"><Label>Tipo de processo</Label><Input name="caseType" defaultValue={template?.caseType} /></div><label className="flex items-center gap-2 self-end pb-2 text-sm"><Input name="isActive" type="checkbox" className="h-5 w-5" defaultChecked={template?.isActive ?? true} />Modelo ativo</label><div className="space-y-2 sm:col-span-2"><Label>Itens — um por linha</Label><Textarea name="items" required rows={10} defaultValue={template?.items.map((item) => item.title).join("\n")} /></div>{error && <p className="text-sm text-red-400 sm:col-span-2">{error}</p>}<Button className="sm:col-span-2" disabled={saving}>{saving && <LoaderCircle className="mr-2 h-4 w-4 animate-spin" />}Salvar modelo</Button></form></div>}</>;
}
