import { Banknote, CircleDollarSign, FileCheck2, Receipt, Scale, TrendingDown, WalletCards } from "lucide-react";
import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatMoney } from "@/lib/format";
import { fetchData } from "@/lib/page-data";

interface Summary { contracted: string; activeContracts: number; upcoming: number; overdue: number; delinquent: number; receivedThisMonth: string; costs: string; completedContracts: number }
export default async function FinanceOverviewPage() { const data = await fetchData<Summary>("/v1/finance/summary"); const cards = [["Honorários contratados", formatMoney(data.contracted), CircleDollarSign, "/financeiro/contratos"], ["Contratos ativos", data.activeContracts, Scale, "/financeiro/contratos?status=ACTIVE"], ["Parcelas a vencer", data.upcoming, WalletCards, "/financeiro/parcelas?view=upcoming"], ["Parcelas vencidas", data.overdue, Receipt, "/financeiro/parcelas?view=overdue"], ["Inadimplentes +15 dias", data.delinquent, TrendingDown, "/financeiro/inadimplencia"], ["Recebido no mês", formatMoney(data.receivedThisMonth), Banknote, "/financeiro/parcelas?view=paid"], ["Custas registradas", formatMoney(data.costs), Receipt, "/financeiro/contratos"], ["Contratos finalizados", data.completedContracts, FileCheck2, "/financeiro/contratos?status=COMPLETED"]] as const; return <><PageHeader eyebrow="Visão financeira" title="Financeiro" description="Resumo executivo; contratos, parcelas e cobranças ficam nos submódulos." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, href]) => <Link key={label} href={href}><Card className="h-full transition-colors hover:border-primary/50"><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm text-muted-foreground">{label}</CardTitle><Icon className="h-4 w-4 text-primary" /></CardHeader><CardContent className="text-2xl font-semibold">{value}</CardContent></Card></Link>)}</div></>; }
