"use client";
import { ArrowRight, LoaderCircle, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { Lookups } from "@/lib/page-data";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";

export function AttendanceConvertPanel({ id, branchId, legalAreaId, lookups }: { id: string; branchId: string; legalAreaId?: string; lookups: Lookups }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>(); const router = useRouter();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const response = await fetch(`/api/v1/attendances/${id}/convert`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ createClient: true, createCase: true, case: { branchId, legalAreaId, caseType: form.get("caseType"), entryDate: form.get("entryDate"), responsibleUserId: form.get("responsibleUserId") || undefined, attorneyId: form.get("attorneyId") || undefined } }) }); if (!response.ok) { const data = await response.json().catch(() => ({})) as { detail?: string; title?: string }; setError(data.detail ?? data.title ?? "Falha na conversão."); setSaving(false); return; } setOpen(false); setSaving(false); router.refresh(); }
  if (!legalAreaId) return <span className="text-xs text-muted-foreground">Defina a área</span>;
  return <><Button size="sm" variant="outline" onClick={() => setOpen(true)}><ArrowRight className="mr-1 h-3 w-3" />Converter</Button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={submit} className="grid w-full max-w-lg gap-4 rounded-xl border bg-card p-6 sm:grid-cols-2"><div className="flex items-center justify-between sm:col-span-2"><h2 className="font-semibold">Gerar cliente e processo</h2><Button type="button" size="icon" variant="ghost" onClick={() => setOpen(false)}><X /></Button></div><div className="space-y-2 sm:col-span-2"><Label>Tipo de processo</Label><Input name="caseType" required /></div><div className="space-y-2"><Label>Data de entrada</Label><Input name="entryDate" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></div><div className="space-y-2"><Label>Responsável interno</Label><select name="responsibleUserId" className="h-10 w-full rounded-md border bg-background px-3"><option value="">Selecione</option>{lookups.users.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="space-y-2 sm:col-span-2"><Label>Advogado responsável</Label><select name="attorneyId" className="h-10 w-full rounded-md border bg-background px-3"><option value="">Selecione</option>{lookups.users.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></div>{error && <p className="text-sm text-red-400 sm:col-span-2">{error}</p>}<Button disabled={saving} className="sm:col-span-2">{saving && <LoaderCircle className="mr-2 h-4 w-4 animate-spin" />}Converter atendimento</Button></form></div>}</>;
}
