"use client";
import { FileUp, LoaderCircle, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { Lookups } from "@/lib/page-data";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";

export function UploadPanel({ lookups }: { lookups: Lookups }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>(); const router = useRouter();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const body = new FormData(event.currentTarget); const response = await fetch("/api/v1/documents", { method: "POST", body }); if (!response.ok) { const problem = await response.json().catch(() => ({})) as { detail?: string; title?: string }; setError(problem.detail ?? problem.title ?? "Falha no upload."); setSaving(false); return; } setOpen(false); setSaving(false); router.refresh(); }
  return <><Button onClick={() => setOpen(true)} className="gap-2"><FileUp className="h-4 w-4" />Anexar documento</Button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={submit} className="grid w-full max-w-xl gap-4 rounded-xl border bg-card p-6 sm:grid-cols-2"><div className="flex items-center justify-between sm:col-span-2"><h2 className="text-lg font-semibold">Anexar documento</h2><Button type="button" variant="ghost" size="icon" onClick={() => setOpen(false)}><X /></Button></div><div className="space-y-2 sm:col-span-2"><Label>Arquivo</Label><Input name="file" type="file" required accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp" /></div><div className="space-y-2"><Label>Nome</Label><Input name="name" required /></div><div className="space-y-2"><Label>Tipo</Label><Input name="type" required placeholder="Identidade, contrato..." /></div><div className="space-y-2"><Label>Filial</Label><select name="branchId" required className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Selecione</option>{lookups.branches.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="space-y-2"><Label>Cliente</Label><select name="clientId" className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Selecione</option>{lookups.clients.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="space-y-2 sm:col-span-2"><Label>Processo (opcional)</Label><select name="caseId" className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Selecione</option>{lookups.cases.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></div>{error && <p className="sm:col-span-2 text-sm text-red-400">{error}</p>}<Button className="sm:col-span-2" disabled={saving}>{saving && <LoaderCircle className="mr-2 h-4 w-4 animate-spin" />}Enviar arquivo</Button></form></div>}</>;
}
