import Link from "next/link";
import { DeadlineCalendar } from "@/components/deadline-calendar";
import { PageHeader } from "@/components/page-header";
import { SearchForm } from "@/components/search-form";
import { ModuleNav } from "@/features/shared/components/module-nav";
import { fetchData, type Lookups } from "@/lib/page-data";

interface DeadlineList { items: Array<{ id: string; caseId: string; title: string; dueAt: string; color: string; client: { name: string }; responsibleUser: { name: string } }> }
type Mode = "month" | "week" | "list";
function key(date: Date) { return date.toISOString().slice(0, 10); }
export default async function CalendarPage({ searchParams }: { searchParams: Promise<{ mode?: Mode; date?: string; branchId?: string; legalAreaId?: string; responsibleId?: string; type?: string }> }) {
  const query = await searchParams; const mode = query.mode ?? "month"; const reference = query.date ? new Date(`${query.date}T12:00:00`) : new Date();
  const from = mode === "month" ? new Date(reference.getFullYear(), reference.getMonth(), 1) : new Date(reference); from.setDate(from.getDate() - from.getDay()); const to = new Date(from); to.setDate(from.getDate() + (mode === "month" ? 42 : mode === "week" ? 7 : 31));
  const apiParams = new URLSearchParams({ pageSize: "100", from: from.toISOString(), to: to.toISOString(), branchId: query.branchId ?? "", legalAreaId: query.legalAreaId ?? "", responsibleId: query.responsibleId ?? "", type: query.type ?? "" });
  const [data, lookups] = await Promise.all([fetchData<DeadlineList>(`/v1/deadlines?${apiParams}`), fetchData<Lookups>("/v1/lookups")]);
  const delta = mode === "month" ? 1 : mode === "week" ? 7 : 1; const previous = new Date(reference); const next = new Date(reference); if (mode === "month") { previous.setMonth(reference.getMonth() - 1); next.setMonth(reference.getMonth() + 1); } else { previous.setDate(reference.getDate() - delta); next.setDate(reference.getDate() + delta); }
  const link = (date: Date) => `/calendario?${new URLSearchParams({ ...Object.fromEntries(Object.entries(query).filter((entry): entry is [string, string] => Boolean(entry[1]))), mode, date: key(date) })}`;
  return <><PageHeader eyebrow={reference.toLocaleDateString("pt-BR", { month: "long", year: "numeric" })} title="Agenda" description="Visões mensal, semanal e em lista dos compromissos jurídicos." action={<div className="flex gap-2"><Link className="rounded-md border px-3 py-2 text-sm" href={link(previous)}>Anterior</Link><Link className="rounded-md border px-3 py-2 text-sm" href={`/calendario?mode=${mode}`}>Hoje</Link><Link className="rounded-md border px-3 py-2 text-sm" href={link(next)}>Próximo</Link></div>} /><ModuleNav items={[{ label: "Mês", href: "/calendario?mode=month" }, { label: "Semana", href: "/calendario?mode=week" }, { label: "Lista", href: "/calendario?mode=list" }]} /><SearchForm><input type="hidden" name="mode" value={mode} /><input type="hidden" name="date" value={key(reference)} /><select name="branchId" defaultValue={query.branchId} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">Todas as filiais</option>{lookups.branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="legalAreaId" defaultValue={query.legalAreaId} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">Todas as áreas</option>{lookups.legalAreas.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="responsibleId" defaultValue={query.responsibleId} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">Todos os responsáveis</option>{lookups.users.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="type" defaultValue={query.type} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">Todos os tipos</option>{["PETICAO_INICIAL", "AUDIENCIA", "RECURSO", "MANIFESTACAO", "ADMINISTRATIVO", "OUTRO"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></SearchForm><DeadlineCalendar items={data.items} mode={mode} referenceDate={key(reference)} /></>;
}
